# Generated by Django 5.0.1 on 2024-01-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_remove_scholarships_course_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarships',
            name='award_amount',
        ),
        migrations.RemoveField(
            model_name='scholarships',
            name='organization',
        ),
        migrations.AddField(
            model_name='scholarships',
            name='Contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
