# Generated by Django 5.0.1 on 2024-01-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_remove_scholarships_award_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
