# Generated by Django 5.0.1 on 2024-01-30 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_scholarshipapplication_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ApprovedScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('original_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_application', to='scholarships.scholarshipapplication')),
            ],
        ),
    ]
