# Generated by Django 5.0.2 on 2024-02-12 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_scholarshipapplication_scholarship_and_more'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='name',
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='userprofile.userprofile'),
        ),
    ]
