# Generated by Django 5.0.2 on 2024-02-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0010_bookmark'),
        ('userprofile', '0003_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='userprofile.userprofile'),
        ),
    ]
