# Generated by Django 5.0.3 on 2024-03-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0018_scholarship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholarship',
        ),
    ]
