# Generated by Django 5.0.3 on 2024-04-01 10:48

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0020_scholarships_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
