# Generated by Django 5.0.3 on 2024-04-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0021_alter_scholarships_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
