# Generated by Django 5.0.3 on 2024-04-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0022_scholarships_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
