# Generated by Django 5.0.2 on 2024-03-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_scholarship_eligibility_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
