# Generated by Django 5.0.2 on 2024-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_scholarship_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(null=True, upload_to='scholarship_images/'),
        ),
    ]
