# Generated by Django 5.0.3 on 2024-04-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_rename_apply_scholarship_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='url',
            new_name='urls',
        ),
    ]
