# Generated by Django 5.0.3 on 2024-04-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0007_rename_url_scholarship_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='urls',
            new_name='url',
        ),
    ]
