# Generated by Django 4.2.9 on 2024-02-02 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholarships', '0007_alter_scholarshipapplication_id_approvedscholarship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('telephone_number', models.CharField(max_length=20)),
                ('optional_contact_phone', models.CharField(max_length=20)),
                ('current_school', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('current_grade_level', models.CharField(max_length=10)),
                ('cumulative_gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('personal_statement', models.TextField()),
                ('optional_essay', models.TextField()),
                ('reference_name', models.CharField(max_length=255)),
                ('reference_email', models.EmailField(max_length=254)),
                ('custom_fields', jsonfield.fields.JSONField(blank=True, null=True)),
                ('Scholarships', models.ManyToManyField(blank=True, to='scholarships.scholarships')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
