# Generated by Django 5.0.2 on 2024-02-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='userprofile',
        ),
    ]
